project:
  type: website
  output-dir: "./_site"
  render:
    - index.qmd
    # English content


website:
  title: "Fundamentals of Data Science"
  page-footer:
    left: |
      Fundamentals of _Data Science_, Chemseddine Berbague.<br>
      Licence {{< fa brands creative-commons >}}<br>
      Code source disponible sur [`Github`](https://github.com/8-chems/lectures)
    right: |
      Site construit with {{< fa brands python >}} and [`Quarto`](https://quarto.org/)<br>
      [Code source disponible sur {{< fa brands github >}} `GitHub`](https://github.com/linogaliana/python-datascientist)
  sidebar:
    - id: chapter_1
      title: "Introduction"
      contents:
        - href: content/chapter_1/index.qmd
          text: "Introduction to data science"
    - id: chapter_2
      title: "Data Pre-processing"
      contents:
        - href: content/chapter_2/index.qmd
          text: "Data pre-processing"

citation:
  title: "Fundamentals of Data Science"
  author: Chemseddine Berbague
  type: book
  doi: "XXXXX"
  url: https://8-chems.github.io/
  issued: 2025


lang: en
