project:
  type: website
  render:
    - index.qmd
    - 404.qmd
    - content/chapter_1/*.qmd
    - content/chapter_2/*.qmd

resources:
  - pdfjs/


profile:
  default: en
  group: [ fr, en ]
  en:
    project:
      output-dir: _site  # English goes to root
    website:
      title: "Fundamentals of Data Science"

  fr:
    project:
      output-dir: _site/fr  # French goes to subfolder
    website:
      title: "Mon Site"


execute:
  cache: true
  keep-ipynb: true

# WEBSITE ARCHITECTURE ---------------------

website:
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: content/images/icon.png
  navbar:
    background: "white"
    search: true
    title: false
    left:
      - file: index.qmd
        text: Home
      - sidebar:chapter_1
      - sidebar:chapter_2


    tools:
      - icon: github
        href: https://github.com/8-chems/lectures
  comments:
    giscus:
      repo: 8-chems/lectures
  twitter-card: true
  site-url: https://8-chems.github.io
  repo-url: https://github.com/8-chems/lectures
  repo-branch: main
  issue-url: https://github.com/8-chems/lectures/issues/new
  repo-actions: [edit, issue]

format:
  html:
    raw-html: true
    embedpdf: true
    include-after-body: build/js/mac.html
    respect-user-color-scheme: true
    theme:
      light: [cosmo, styles/custom.scss, styles/custom-light.scss]
      dark: [cosmo, styles/custom.scss, styles/custom-dark.scss]
    css: styles/styles.css
    toc: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    highlight-style: monokai
    anchor-sections: true
  ipynb: default



# PAGE OPTIONS ---------------------

filters:
  - at: pre-ast
    path: _extensions/linogaliana/lang-switch/lang-notebook.lua
  - at: pre-ast
    path: _extensions/linogaliana/callout/callout-notebook.lua
  - at: pre-ast
    path: _extensions/linogaliana/lang-switch/warninglang.lua
  - include-code-files
  - build/replace-title.lua
  - _extensions/linogaliana/details-iframe/details.lua
  - _extensions/linogaliana/lang-switch/button.lua
  - _extensions/slide-viewer/slide-viewer.lua

crossref:
  chapters: true

date-format: iso
number-sections: true
wrap: preserve
format-links: false
validate-yaml: false
keep-ipynb: true
lightbox: auto
google-scholar: true
highlight-style: a11y

