project:
  type: website
  output-dir: "./_site/en"
  render:
    - index.qmd
    # English content


website:
  title: "Python for data science"
  page-footer:
    left: |
      Python pour la _data science_, Lino Galiana.<br>
      Licence {{< fa brands creative-commons >}}<br>
      Code source disponible sur [`Github`](https://github.com/linogaliana/python-datascientist)
    right: |
      Site construit avec {{< fa brands python >}} et [`Quarto`](https://quarto.org/)<br>
      [Code source disponible sur {{< fa brands github >}} `GitHub`](https://github.com/linogaliana/python-datascientist)
  sidebar:
    - id: introduction
      title: "Introduction"
      #collapse-level: 2
      contents:
        - href: content/getting-started/index.qmd
          text: "Introduction"
    - id: manipulation
      title: "Manipuler"
      #collapse-level: 2
      contents:
        - href: content/manipulation/index.qmd
          text: "Introduction"
        - content/manipulation/01_numpy.qmd
        - content/manipulation/02_pandas_intro.qmd
        - href: content/manipulation/02_pandas_suite.qmd
          text: "Manipuler des données avec Pandas"
        - content/manipulation/03_geopandas_intro.qmd
        - content/manipulation/04a_webscraping_TP.qmd
        - content/manipulation/04c_API_TP.qmd
        - content/manipulation/04b_regex_TP.qmd
        - content/manipulation/05_parquet_s3.qmd

citation:
  title: "Python pour la data science"
  author: Lino Galiana
  type: book
  doi: "10.5281/zenodo.8229676"
  url: https://pythonds.linogaliana.fr/
  issued: 2023


lang: en
